sudo: false
language: cpp

branches:
  except: /msvc.*/

addons:
  apt:
    packages:
      - g++-6
      - g++-5
    sources: &sources
      - ubuntu-toolchain-r-test


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0


# More complete test matrix
matrix:
  include:
    # Clang 3.6
    - os: linux
      env: LLVM_VERSION=3.6.2
      compiler: clang

    # Clang 3.7
    - os: linux
      env: LLVM_VERSION=3.7.1
      compiler: clang

    # Clang 3.8
    - os: linux
      env: LLVM_VERSION=3.8.0
      compiler: clang

    # GCC 5
    - os: linux
      env: COMPILER=g++-5
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6
      compiler: gcc

    # Xcode 6.4
    - os: osx
      env:
      osx_image: xcode6.4

    # Xcode 7.3
    - os: osx
      env:
      osx_image: xcode7.3

    # Xcode 8
    - os: osx
      env:
      osx_image: xcode8

    ##########################################################################
    # C++17
    ##########################################################################

    # Clang 3.6
    - os: linux
      env: LLVM_VERSION=3.6.2   CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"
      compiler: clang

    # Clang 3.7
    - os: linux
      env: LLVM_VERSION=3.7.1   CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"
      compiler: clang

    # Clang 3.8
    - os: linux
      env: LLVM_VERSION=3.8.0   CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"
      compiler: clang

    # GCC 6
    - os: linux
      env: COMPILER=g++-6       CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"
      compiler: gcc

    # Xcode 6.4
    - os: osx
      env:
      osx_image: xcode6.4       CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"

    # Xcode 7.3
    - os: osx
      env:
      osx_image: xcode7.3       CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"

    # Xcode 8
    - os: osx
      env:
      osx_image: xcode8         CMAKE_OPTIONS="-DENABLE_CXX_VERSION=c++1z"


install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Setup default versions and override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  ############################################################################
  # Install Clang, libc++ and libc++abi
  ############################################################################
  - |
    if [[ "${LLVM_VERSION}" != "" ]]; then
      LLVM_DIR=${DEPS_DIR}/llvm-${LLVM_VERSION}
      if [[ -z "$(ls -A ${LLVM_DIR})" ]]; then
        LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
        LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
        LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
        CLANG_URL="http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz"
        mkdir -p ${LLVM_DIR} ${LLVM_DIR}/build ${LLVM_DIR}/projects/libcxx ${LLVM_DIR}/projects/libcxxabi ${LLVM_DIR}/clang
        travis_retry wget --quiet -O - ${LLVM_URL}      | tar --strip-components=1 -xJ -C ${LLVM_DIR}
        travis_retry wget --quiet -O - ${LIBCXX_URL}    | tar --strip-components=1 -xJ -C ${LLVM_DIR}/projects/libcxx
        travis_retry wget --quiet -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C ${LLVM_DIR}/projects/libcxxabi
        travis_retry wget --quiet -O - ${CLANG_URL}     | tar --strip-components=1 -xJ -C ${LLVM_DIR}/clang
        (cd ${LLVM_DIR}/build && cmake .. -DCMAKE_INSTALL_PREFIX=${LLVM_DIR}/install -DCMAKE_CXX_COMPILER=clang++)
        (cd ${LLVM_DIR}/build/projects/libcxx && make install -j2)
        (cd ${LLVM_DIR}/build/projects/libcxxabi && make install -j2)
      fi
      export CXXFLAGS="-nostdinc++ -isystem ${LLVM_DIR}/install/include/c++/v1"
      export LDFLAGS="-L ${LLVM_DIR}/install/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LLVM_DIR}/install/lib"
      export PATH="${LLVM_DIR}/clang/bin:${PATH}"
    fi
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})


script:
- (cd build && make VERBOSE=1 && ctest -V)
